server:
  port: 8081

spring:
  application:
    name: match-service
  data:
    mongodb:
      authentication-database: admin
      repositories:
        enabled: true
      host: 0.0.0.0
      port: 27017
      database: service_match
      username: root
      password: root

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5555/auth/user